apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-website
  labels:
    app: nginx-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-website
  template:
    metadata:
      labels:
        app: nginx-website
    spec:
      containers:
      - name: nginx-website
        image: peterbb148/nginx-website
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-website-service
spec:
  selector:
    app: nginx-website
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-website-ingress
  annotations:
    kubernetes.io/ingress-class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx-website-service
          servicePort: 80
